# Generated by Django 3.1.4 on 2020-12-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_network', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaroapp.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('year', models.IntegerField(blank=True, default=2020)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('genre', models.IntegerField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('release', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('trailer', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('low_price', models.FloatField(blank=True)),
                ('high_price', models.FloatField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('cinema_movie_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='avaroapp.cinemamovie')),
            ],
        ),
        migrations.AddField(
            model_name='cinemamovie',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaroapp.movie'),
        ),
        migrations.AddConstraint(
            model_name='cinema',
            constraint=models.UniqueConstraint(fields=('cinema_network', 'name'), name='cinema_name'),
        ),
    ]
