# Generated by Django 3.1.4 on 2020-12-06 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='name',
            new_name='location',
        ),
    ]
