# Generated by Django 3.1.4 on 2020-12-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0003_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.IntegerField(blank=True, default=2020)),
                ('link', models.IntegerField(blank=True, default=2020)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=150)),
                ('cinema_id', models.IntegerField(blank=True, default=2020)),
                ('start_date', models.IntegerField(blank=True, default=2020)),
                ('end_date', models.IntegerField(blank=True, default=2020)),
                ('high_price', models.IntegerField(blank=True, default=2020)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_movie', models.CharField(max_length=150)),
                ('date', models.IntegerField(blank=True, default=2020)),
                ('time', models.IntegerField(blank=True, default=2020)),
                ('low_price', models.IntegerField(blank=True, default=2020)),
                ('high_price', models.IntegerField(blank=True, default=2020)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.IntegerField(blank=True, default=2020),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, default=2020),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(blank=True, default=2020),
        ),
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.IntegerField(blank=True, default=2020),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(blank=True, default=2020),
        ),
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.IntegerField(blank=True, default=2020),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.IntegerField(blank=True, default=2020),
        ),
    ]
