# Generated by Django 3.1.4 on 2020-12-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0005_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
