# Generated by Django 3.1.4 on 2020-12-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0006_auto_20201205_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='cinema_network',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cinema',
            unique_together={('cinema_network', 'name')},
        ),
    ]
