# Generated by Django 3.1.4 on 2020-12-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0006_auto_20201206_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemamovie',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinemamovie',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
