# Generated by Django 3.1.4 on 2020-12-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaroapp', '0007_auto_20201205_0608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cinema',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cinema',
            constraint=models.UniqueConstraint(fields=('cinema_network', 'name'), name='cinema_name'),
        ),
    ]
